language: cpp
dist: bionic

addons:
  apt:
    sources: 
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libacl1-dev
      - libcap-dev
      - libsqlite3-dev
      - zlib1g-dev
  coverity_scan:
    project:
      name: "filcompare"
      description: "Build submitted via Travis CI"
    build_command_prepend: "cmake -D CMAKE_EXPORT_COMPILE_COMMANDS=ON -D CMAKE_BUILD_TYPE:STRING=Debug . "
    build_command:   "cmake --build . -- -j2"
    branch_pattern: coverity_scan
      
matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - GCC_VER="7" CPPCHECK=1 CMAKE_OPTIONS="-D RUN_FUZZY_TESTS:BOOL=TRUE"
    - os: linux
      compiler: clang
      env:
        - CMAKE_OPTIONS=" -D DYNLOAD_ENABLED:BOOL=FALSE -D MULTITHREAD_SUPPORT_ENABLED:BOOL=FALSE -D CMAKE_EXPORT_COMPILE_COMMANDS=ON -D USE_STD_MAKE_SHARED:BOOL=TRUE" BUILD_ONLY=1
  
before_install:
  - if [ "${GCC_VER}" != "" ]; then export CXX="g++-$GCC_VER" CC="gcc-$GCC_VER" GCOV="gcov-$GCC_VER" ; fi
  - pip install --user cpp-coveralls

script: 
  - cmake -D CMAKE_BUILD_TYPE:STRING=Debug $CMAKE_OPTIONS . 
  - cmake --build .